version: "3"
services:
  mysql:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  app:
    build: .
    volumes:
      - .:/explain_to_markdown_table
    environment:
      - LANG=ja_JP.UTF-8
      - LC_CTYPE=ja_JP.UTF-8
    tty: true

